DECLARE

Tcoderror NUMBER;
SUMA NUMBER := 0;
Ttexterror VARCHAR2(100);
PLSQLBLOCK VARCHAR2(500);

BEGIN

FOR TABLA IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'INVERSIONES_%')
LOOP

    PLSQLBLOCK := 'SELECT SUM(CANTIDAD) FROM '  || TABLA.TABLE_NAME || '';
    EXECUTE IMMEDIATE PLSQLBLOCK INTO SUMA;

    PLSQLBLOCK := 'BEGIN INSERT INTO SUMAEMPRESA VALUES(:1,:2); END;';
    EXECUTE IMMEDIATE PLSQLBLOCK USING IN TABLA.TABLE_NAME , SUMA; 

END LOOP;

EXCEPTION

  WHEN OTHERS THEN

  Tcoderror:= SQLCODE;
  Ttexterror:= SUBSTR(SQLERRM,1, 100);
  DBMS_output.put_line('Sale por una excepcion: ' || Tcoderror ||   '  -- ' || Ttexterror );

END;
