--DROP TABLE LOGSUMAS;
--CREATE TABLE LOGSUMAS (FECHA_HORA DATE, LITERAL CHAR(1), CANTIDAD FLOAT, NOMBREE CHAR(50));

INSERT INTO SUMAEMPRESA VALUES('GENERAL MOTORS',10000);

CREATE OR REPLACE TRIGGER TRI_LOG AFTER INSERT OR UPDATE ON SUMAEMPRESA
FOR EACH ROW
DECLARE

Tcoderror NUMBER;
Ttexterror VARCHAR2(100);
CANTIDAD_MUY_GRANDE EXCEPTION;

BEGIN

    IF (:NEW.CANTIDAD > 100000000) THEN
        --RAISE CANTIDAD_MUY_GRANDE;
        -- RANGO (-20000) - (-20999)
        RAISE_APPLICATION_ERROR(-20000,'SE INTENTO INSERTAR UNA CANTIDAD SUPERIOR A 100000000.');
    END IF;

    IF INSERTING THEN
    
        INSERT INTO LOGSUMAS VALUES(SYSDATE,'I',:NEW.CANTIDAD,:NEW.NOMBREE);
    
    END IF;
    
    IF UPDATING THEN
    
        INSERT INTO LOGSUMAS VALUES(SYSDATE,'U',:NEW.CANTIDAD,:NEW.NOMBREE);
    
    END IF;

/*
EXCEPTION

    WHEN CANTIDAD_MUY_GRANDE THEN

        DBMS_output.put_line('SE HA INTRODUCIR UNA CANTIDAD MAYOR QUE 100000000.');

  WHEN OTHERS THEN

  Tcoderror:= SQLCODE;
  Ttexterror:= SUBSTR(SQLERRM,1, 100);
  DBMS_output.put_line('Sale por una excepcion: ' || Tcoderror ||   '  -- ' || Ttexterror );
*/

END;