DROP TABLE Empresa CASCADE CONSTRAINTS;
DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE Moroso CASCADE CONSTRAINTS;
DROP TABLE Invierte CASCADE CONSTRAINTS;
DROP TABLE Tarjeta CASCADE CONSTRAINTS;
DROP TABLE Compras CASCADE CONSTRAINTS;
DROP TABLE Puesto CASCADE CONSTRAINTS;
DROP TABLE TieneT CASCADE CONSTRAINTS;
